name: musicassistant
services:
  musicassistant:
    environment:
      LOG_LEVEL: info
    image: ghcr.io/music-assistant/server:latest
    deploy:
      resources:
        reservations:
          memory: 256M
    network_mode: host
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /data
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
      - type: bind
        source: /run/dbus
        target: /run/dbus
        read_only: true    
    cap-add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
    privileged: true
    x-casaos:
      envs:
        - container: TZ
          description:
            en_AU: TimeZone
        - container: PUID
          description:
            en_AU: Run MusicAssistant as specified uid.
        - container: PGID
          description:
            en_AU: Run MusicAssistant as specified gid.
      volumes:
        - container: /data
          description:
            en_AU: MusicAssistant data directory.
    container_name: MusicAssistant
x-casaos:
  architectures:
    - amd64
    - arm64
    - arm
  main: MusicAssistant
  author: darth3pio
  category: Media
  description:
    en_AU: |
      The Music Assistant server is a free, opensource Media library manager that connects to your streaming services and a wide range 
      of connected speakers. The server is the beating heart, the core of Music Assistant and it keeps track of your music sources. It must 
      run on an always-on device like a Raspberry Pi, a NAS or an Intel NUC or alike. The server can access multiple music providers and 
      stream to multiple player types.

      **Key Features:**
      - Supports multiple music sources through a provider implementation
      - Many popular streaming services are supported, as well as local files
      - Automatically matches music on different providers (track linking)
      - Fetches metadata for extended artist information
      - Keeps track of the entire music library in a compact database
      - Gapless, crossfade and volume normalization support for all players
      - Playback synchronisation is possible for supported players
      - Announcements during playback supported
      - Transfer of playback between players supported
      - Truly hassle free streaming of your favourite music to players, no advanced knowledge required
      - Rich User interface (Progressive Web App) powered by logoVueJS 3

      **Learn More:**
      - [Music Assistant Official Website](https://www.music-assistant.io/)
  thumbnail: https://cdn.jsdelivr.net/gh/darth3pio/darth3pio-casaos@main/Apps/MusicAssistant-Nightly/thumbnail.png
  tips: {}
  title:
    en_US: Home Assistant
  index: /
  port_map: "8095"
