name: build documentation and publish

on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: remove all file except docker yaml
        run: find . -type f -not \( -name '*.yaml' -or -name '*.yml' \) -delete
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB2 }}
        with:
          source-directory: './Apps'
          destination-github-username: 'darth3pio'
          destination-repository-name: '-casaos'
          user-email: duncan.macfarlane@outlook.com.au
          target-directory: './Apps'
      - name: Copycat
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.API_TOKEN_GITHUB2 }}
          src_path: ./recommend-list.json
          dst_owner: darth3pio
          dst_repo_name: -casaos
          email: duncan.macfarlane@outlook.com.au
          src_branch: main
          dst_branch: main
      - name: Error Handling
        if: ${{ failure() }}
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"msg_type":"text","content":{"text":"CasaOS-AppStore build and publish error"}}' ${{ secrets.APPSTORE_ROBOT_URL }} 

